AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

# Ignore Metrics/BlockLength for files in the spec/ directory
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - "spec/**/*"
    - "rbar.gemspec"
